select count(*) from HEALTH_PLAN_NEW;;

select * from team1.hidata;

select count(*) from team1.hidata;




select plan_id from team1.hidata;


Create table team1.hidata_new(
PLAN_ID	VARCHAR(25),
PLAN_MARKETING_NAME	VARCHAR(100),
STATE_CODE	VARCHAR(25),
COUNTY_NAME	VARCHAR(25),
METAL_LEVEL	VARCHAR(25),
CHILD_ONLY_OFFERING VARCHAR(50),
ACCREDIDATION	VARCHAR(25),
ADULT_DENTAL	VARCHAR(25),
CHILD_DENTAL	VARCHAR(25),
PREMIUM_CHILD	VARCHAR(25),
PREM_ADULT_IND_AGE_21	VARCHAR(25),
PREM_ADULT_IND_AGE_27	VARCHAR(25),
PREM_ADULT_IND_AGE_30	VARCHAR(25),
PREM_ADULT_IND_AGE_40	VARCHAR(25),
PREM_ADULT_IND_AGE_50	VARCHAR(25),
PREM_ADULT_IND_AGE_60	VARCHAR(25),
PREM_COUPLE_21	VARCHAR(25),
PREM_COUPLE_30	VARCHAR(25),
PREM_COUPLE_40	VARCHAR(25),
PREM_COUPLE_50	VARCHAR(25),
PREM_COUPLE_60	VARCHAR(25),
COUPLE1_CHILD_AGE_21	VARCHAR(25),
COUPLE1_CHILD_AGE_30	VARCHAR(25),
COUPLE1_CHILD_AGE_40	VARCHAR(25),
COUPLE1_CHILD_AGE_50	VARCHAR(25),
COUPLE2_CHILDREN_AGE_21	VARCHAR(25),
COUPLE2_CHILDREN_AGE_30	VARCHAR(25),
COUPLE2_CHILDREN_AGE_40	VARCHAR(25),
COUPLE2_CHILDREN_AGE_50	VARCHAR(25),
COUPLE3_OR_MORE_CHILDREN_AGE_21	VARCHAR(25),
COUPLE3_OR_MORE_CHILDREN_AGE_30	VARCHAR(25),
COUPLE3_OR_MORE_CHILDREN_AGE_40	VARCHAR(25),
COUPLE3_OR_MORE_CHILDREN_AGE_50	VARCHAR(25),
IND1_CHILD_AGE_21	VARCHAR(25),
IND1_CHILD_AGE_30	VARCHAR(25),
IND1_CHILD_AGE_40	VARCHAR(25),
IND1_CHILD_AGE_50	VARCHAR(25),
IND2_CHILD_AGE_21	VARCHAR(25),
IND2_CHILD_AGE_30	VARCHAR(25),
IND2_CHILD_AGE_40	VARCHAR(25),
IND2_CHILD_AGE_50	VARCHAR(25),
IND3_OR_MORE_CHILDREN_AGE_21	VARCHAR(25),
IND3_OR_MORE_CHILDREN_AGE_30	VARCHAR(25),
IND3_OR_MORE_CHILDREN_AGE_40	VARCHAR(25),
IND3_OR_MORE_CHILDREN_AGE_50	VARCHAR(25),
MED_DED_IND_STD	VARCHAR(25),
DRUG_DED_IND_STD	VARCHAR(25),
MED_DED_FAM_STD	VARCHAR(25),
DRUG_DED_FAM_STD	VARCHAR(25),
MED_DED_FAM_PER_STD	VARCHAR(25),
DRUG_DED_FAM_PER_STD	VARCHAR(25),
MED_MAX_PKT_IND_STD	VARCHAR(25),
DRUG_MAX_PKT_IND_STD	VARCHAR(25),
MED_MAX_PKT_FAM_STD	VARCHAR(25),
DRUG_MAX_PKT_FAM_STD	VARCHAR(25),
MED_MAX_PKT_FAM_PER_STD	VARCHAR(25),
DRUG_MAX_PKT_FAM_PER_STD	VARCHAR(25),
PRIM_CARE_PHYS_STD	VARCHAR(100),
SPECIALIST_STD	VARCHAR(50),
EMERG_ROOM_STD	VARCHAR(100),
INPATIENT_FACILITY_STD	VARCHAR(100),
INPATIENT_PHYSICIAN_STD	VARCHAR(50),
GEN_DRUGS_STD	VARCHAR(50),
PREF_BRAND_DRUGS_STD	VARCHAR(50),
NONPREF_BRAND_DRUGS_STD	VARCHAR(100),
SPEC_DRUGS_STD	VARCHAR(100));

select * from team1.hidata_new;

select count(distinct plan_id) from team1.hidata_new;   //3003

select count(*) from team1.hidata_new;  // 65542

select plan_id,state_code,county_name,metal_level, count(*) as TOTAL_COUNT
from team1.hidata_new
group by plan_id, state_code, county_name, metal_level;

select plan_id,state_code,county_name, count(*) as TOTAL_COUNT
from team1.hidata_new
group by plan_id, state_code, county_name;


select plan_id,state_code, count(*) as TOTAL_COUNT
from team1.hidata_new
group by plan_id, state_code;


select sum(total_count)
from (select plan_id,state_code, count(*) as TOTAL_COUNT
from team1.hidata_new
group by plan_id, state_code);  //65542


select state_code, prem_couple_21,MED_DED_FAM_STD,PREF_BRAND_DRUGS_STD
from team1.hidata_new;

select * from team1.hidata_new;








